/**
 * Core modules shared between all run modes.
 */

export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type PromptOptions,
	type SessionStats,
} from "./agent-session.js";
export {
	AgentSessionRuntime,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	createAgentSessionRuntime,
} from "./agent-session-runtime.js";
export {
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionServicesOptions,
	createAgentSessionFromServices,
	createAgentSessionServices,
} from "./agent-session-services.js";
export { type BashExecutorOptions, type BashResult, executeBashWithOperations } from "./bash-executor.js";
export type { CompactionResult } from "./compaction/index.js";
export { createEventBus, type EventBus, type EventBusController } from "./event-bus.js";
// Extensions system
export {
	type AgentEndEvent,
	type AgentStartEvent,
	type AgentToolResult,
	type AgentToolUpdateCallback,
	type BeforeAgentStartEvent,
	type BeforeAgentStartEventResult,
	type BuildSystemPromptOptions,
	type ContextEvent,
	defineTool,
	discoverAndLoadExtensions,
	type ExecOptions,
	type ExecResult,
	type Extension,
	type ExtensionAPI,
	type ExtensionCommandContext,
	type ExtensionContext,
	type ExtensionError,
	type ExtensionEvent,
	type ExtensionFactory,
	type ExtensionFlag,
	type ExtensionHandler,
	ExtensionRunner,
	type ExtensionShortcut,
	type ExtensionUIContext,
	type LoadExtensionsResult,
	type MessageRenderer,
	type RegisteredCommand,
	type SessionBeforeCompactEvent,
	type SessionBeforeForkEvent,
	type SessionBeforeSwitchEvent,
	type SessionBeforeTreeEvent,
	type SessionCompactEvent,
	type SessionShutdownEvent,
	type SessionStartEvent,
	type SessionTreeEvent,
	type ToolCallEvent,
	type ToolCallEventResult,
	type ToolDefinition,
	type ToolRenderResultOptions,
	type ToolResultEvent,
	type TurnEndEvent,
	type TurnStartEvent,
	type WorkingIndicatorOptions,
} from "./extensions/index.js";
export {
	buildHaloTraceIndex,
	createHaloExtension,
	createSpanId,
	createTraceId,
	defaultHaloTracePath,
	ensureHaloTraceIndex,
	type HaloActiveSpan,
	type HaloDatasetOverview,
	type HaloExtensionOptions,
	type HaloOversizedTraceSummary,
	type HaloSpanRecord,
	type HaloSpanResource,
	type HaloSpanScope,
	type HaloSpanStatus,
	type HaloTraceCountResult,
	type HaloTraceFilters,
	type HaloTraceIndexMeta,
	type HaloTraceIndexRow,
	type HaloTraceQueryResult,
	type HaloTraceSearchResult,
	HaloTraceStore,
	type HaloTraceSummary,
	type HaloTraceView,
	HaloTraceWriter,
	type HaloTraceWriterOptions,
	haloIndexMetaPathFor,
	haloIndexPathFor,
	loadHaloTraceIndex,
	type RegisterHaloTraceToolsOptions,
	registerHaloTraceTools,
	summarizeAgentMessage,
	summarizeContent,
	summarizeHaloToolOutput,
	summarizeToolResult,
	toOtelTime,
	truncateUnknown,
} from "./halo/index.js";
export {
	createPiMemExtension,
	defaultPiMemPath,
	extractMemoryCandidatesFromMessage,
	extractMemoryCandidatesFromToolResult,
	formatInjectedMemories,
	type PiMemCitation,
	type PiMemExtensionOptions,
	type PiMemRecord,
	type PiMemRecordType,
	type PiMemResolvedSettings,
	type PiMemSearchInput,
	type PiMemSettings,
	PiMemStore,
	redactLikelySecrets,
	registerPiMemTools,
} from "./pi-mem/index.js";
export { createSyntheticSourceInfo } from "./source-info.js";
